// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Cats
{
    public int Id { get; set; }

    public string CatId { get; set; }

    public int Width { get; set; }

    public int Height { get; set; }

    public byte[] Image { get; set; }

    public DateTime Created { get; set; }

    public virtual ICollection<Tags> TagEntity { get; set; } = new List<Tags>();
}