// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Tags
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime Created { get; set; }

    public virtual ICollection<Cats> CatEntity { get; set; } = new List<Cats>();
}