version: '3.4'

services:
  catapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - catnet
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "1990"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - catnet
    restart: always

networks:
  catnet:
    driver: bridge
